version: "3"
name: "scamazon"

networks:
  my_network:
    driver: bridge

volumes:
  mongo-data:

services:
  product-catalog-service:
    build: ./backend
    # image: passwordnotsafe/produkt-catalog-service:master
    networks:
      - my_network
    ports:
      - "4005:4005"
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo
    restart: always
    networks:
      - my_network
    volumes:
      - ./mongo-data:/data/db
      - ./init/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: echo 'mongo.runCommand("ping").ok' | mongosh mongo:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 200s
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: allProducts

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8084:8081
    networks:
      - my_network
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
