version: '3'
name: "scamazon"

networks:
  my_network:
    driver: bridge

services:

  produkt-catalog-service:
    build: ./backend
    networks:
      - my_network
    depends_on:
      mongo-produkt-catalog-service:
        condition: service_healthy

  prometheus-produkt-catalog-service:
    image: prom/prometheus:latest
    ports:
      - "9094:9090"
    networks:
      - my_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml

  mongo-produkt-catalog-service:
    image: mongo
    restart: always
    networks:
      - my_network
    volumes:
      - ./mongo-data:/data/db
    healthcheck:
      test: echo 'mongo-produkt-catalog-service.runCommand("ping").ok' | mongosh mongo-produkt-catalog-service:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 40s
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express-produkt-catalog-service:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    networks:
      - my_network
    depends_on:
      mongo-produkt-catalog-service:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-produkt-catalog-service:27017/
