global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:4007']
  - job_name: 'home-page-service'
    static_configs:
      - targets: ['home-page-service:4004']
  - job_name: 'user-management-service'
    static_configs:
      - targets: ['product-service:4005']