name: Docker Build and Push

on:
  push:
    branches:
      - 11-environment-paramates-to-backend-file
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t passwordnotsafe/produkt-catalog-service:${{ github.sha }} ./backend

      - name: Push Docker Image
        run: |
          docker push passwordnotsafe/produkt-catalog-service:${{ github.sha }}
