name: Docker Image CI

on:
  push:
    branches:
      - 10-test-github-action-building-docker-image-and-publish

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}

        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag passwordnotsafe/product-servce:1.0.0

      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USERNAME}}/produkt-catalog-service
