name: Docker Publish

on:
  push:
    branches:
      - 10-test-github-action-building-docker-image-and-publish # Adjust this branch name as needed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t passwordnotsafe/produkt-catalog-service:latest .
          docker tag passwordnotsafe/produkt-catalog-service:latest passwordnotsafe/produkt-catalog-service:$(date +"%Y%m%d%H%M%S")

      - name: Push Docker image to Docker Hub
        run: |
          docker push passwordnotsafe/produkt-catalog-service:latest
          docker push passwordnotsafe/produkt-catalog-service:$(date +"%Y%m%d%H%M%S")
