name: Docker Build and Push

on:
  push:
    branches:
      - 11-environment-paramates-to-backend-file
      - main
  pull_request:
    branches:
      - main

permissions:
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t passwordnotsafe/produkt-catalog-service ./backend
          docker build -t passwordnotsafe/produkt-catalog-service:${{ github.sha }} ./backend

      - name: Push Docker Image
        run: |
          docker push passwordnotsafe/produkt-catalog-service
          docker push passwordnotsafe/produkt-catalog-service:${{ github.sha }}
      
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '15s' 

      - name: Trigger fetch new sha update to k8 deployment file.
        run: |
          curl --request POST \
            --url 'https://api.github.com/repos/DevOps22-Grupp1/scamazon/actions/workflows/product-update-sha.yml/dispatches' \
            -H "Accept: application/vnd.github+json" \
            -H 'Authorization: Bearer ${{secrets.TOKEN}}' \
            -d '{"ref":"main"}'
